### ISSUE TITLE
ImportError: cannot import name 'ensure_future'

### ISSUE THREAD

**Issue by creasty** [miyakogi/livemark#1]
```
in ~g/creasty/dotfiles on master
❯ python3 /Users/ykiwng/go/src/github.com/creasty/dotfiles/vim/bundle/livemark.vim/plugin/run.py --browser=google-chrome --browser-port=8089 --vim-port=8090 --js-files "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" "/Users/ykiwng/go/src/github.com/creasty/dotfiles/vim/bundle/livemark.vim/static/bootstrap.min.js" --css-files "/Users/ykiwng/go/src/github.com/creasty/dotfiles/vim/bundle/livemark.vim/static/bootstrap.min.css"
78885%                                                                                                                                                                                                                                                                                                                                                                      
in ~g/creasty/dotfiles on master
❯ Traceback (most recent call last):
  File "/Users/ykiwng/go/src/github.com/creasty/dotfiles/vim/bundle/livemark.vim/plugin/livemark/livemark.py", line 22, in <module>
    from wdom.tag import Div, Style, H2, Script, WebElement
  File "/Users/ykiwng/go/src/github.com/creasty/dotfiles/vim/bundle/livemark.vim/plugin/livemark/wdom/wdom/tag.py", line 8, in <module>
    from asyncio import coroutine, ensure_future, iscoroutine, Future
ImportError: cannot import name 'ensure_future'
```

There was no error on vim in this case, It just didn't work.

**Comment by creasty** [comment]
Although the problem per se was fixed by upgrading python3, I wish you could give me a message on vim.
http://stackoverflow.com/questions/30854576/ensure-future-not-available-in-module-asyncio

**Comment by miyakogi** [comment]
Thank you for reporting.

I agree, the errors on python should be caught and reported in vim.
I will fix it on livemark.vim.

And I'm sorry, information about supported python version was not enough.
I have updated README and only support python > 3.5.1.
This library works with python3.4.4 now, but I will drop its support, to use async/await introduced in python3.5.
